apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: tomcatwebapp
spec:
 replicas: 2
 template:
     metadata:
       labels:
         app: web
     spec:
      containers:
        - name: tomcatwebapp
          image: 649636635951.dkr.ecr.eu-west-1.amazonaws.com/tomcatwebapp:latest
          ports:
            - containerPort: 8080